spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UniGather
    username: root
    password: Hyk200302194525
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl